"""Alter incident report tbl & create embedding tbl

Revision ID: 4fe22985229b
Revises: 7aee3524f65c
Create Date: 2025-04-08 17:20:36.595017

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector


# revision identifiers, used by Alembic.
revision: str = "4fe22985229b"
down_revision: Union[str, None] = "7aee3524f65c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE EXTENSION IF NOT EXISTS vector;")
    op.create_table(
        "incident_report_embedding",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("incident_report_id", sa.Integer(), nullable=False),
        sa.Column(
            "embedding", pgvector.sqlalchemy.vector.VECTOR(dim=1024), nullable=False
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_incident_report_embedding_id"),
        "incident_report_embedding",
        ["id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_incident_report_embedding_incident_report_id"),
        "incident_report_embedding",
        ["incident_report_id"],
        unique=False,
    )
    op.add_column(
        "incident_report", sa.Column("explanation", sa.String(), nullable=False)
    )
    op.add_column("incident_report", sa.Column("reported_by", sa.UUID(), nullable=True))
    op.add_column(
        "incident_report",
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )
    op.add_column(
        "incident_report",
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("incident_report", "updated_at")
    op.drop_column("incident_report", "created_at")
    op.drop_column("incident_report", "reported_by")
    op.drop_column("incident_report", "explanation")
    op.drop_index(
        op.f("ix_incident_report_embedding_incident_report_id"),
        table_name="incident_report_embedding",
    )
    op.drop_index(
        op.f("ix_incident_report_embedding_id"), table_name="incident_report_embedding"
    )
    op.drop_table("incident_report_embedding")
    op.execute("DROP EXTENSION IF EXISTS vector;")
    # ### end Alembic commands ###
