"""remove relation

Revision ID: 8178017d07a3
Revises: 3d6bdd28651c
Create Date: 2025-04-10 20:47:48.002027

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8178017d07a3'
down_revision: Union[str, None] = '3d6bdd28651c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('incident_report_chat_session_id_fkey', 'incident_report', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('incident_report_chat_session_id_fkey', 'incident_report', 'chat_session', ['chat_session_id'], ['id'])
    # ### end Alembic commands ###
